# Generated by Django 2.2.3 on 2019-08-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogReg', '0003_auto_20190820_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
